# Theme
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "contrast"

# Site Settings
locale: "en-US"
title: "oroques.dev"
title_separator: "|"
name: "Olivier Roques"
description: "My personal website."
url: "https://oroques.dev"
repository: "oroques/oroques.dev"
breadcrumbs: false
breadcrumb_home_label: "Home"
breadcrumb_separator: "/"
words_per_minute: 200
search: true
search_full_content: true
search_provider: lunr

# Site Author
author:
  name: "Olivier Roques"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I'm a MSc student in Network & System Security."
  location: "Paris, France"
  email:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/olivier-roques"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ojroques"
    - label: "Git Server"
      icon: "fab fa-fw fa-git"
      url: "https://git.oroques.dev/"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/olivier-roques"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ojroques"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      toc: false
      toc_label: "Contents"
      toc_icon: "bars"
