title = "Olivier Roques"
baseURL = "https://oroques.dev"
theme = "researcher"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]
enableEmoji = true

[params]
  author = "Olivier Roques"
  description = "My personal website."
  favicon = "favicon.ico"
  [params.footer]
    text = "By Olivier Roques"
    url = "https://github.com/ojroques/oroques.dev"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume_en.pdf"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3
  [[menu.main]]
    name = "Notes"
    url = "/notes"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
